jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
auth:
  session:
    ttl-millis: ${JWT_EXPIRATION}
server:
  port: 8080
spring:
  application:
    name: InvestingTracker
  webflux:
    base-path: /api
  ssl:
    bundle:
      pem:
        mongodb-bundle:
          keystore:
            certificate: ${MONGO_CERT_PATH}
            private-key: ${MONGO_CERT_PATH}
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}
      ssl:
        enabled: true
        bundle: mongodb-bundle
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      timeout: ${REDIS_TIMEOUT}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          localhost: ${MAIL_LOCALHOST:sandbox6f1a2edd320341c7acb394d2ed82bcc9.mailgun.org}
  twilio:
    account-sid: ${TWILIO_ACCOUNT_SID}
    auth-token: ${TWILIO_AUTH_TOKEN}
    from-number: ${TWILIO_FROM_NUMBER}
    from-whatsapp: ${TWILIO_FROM_WHATSAPP}
app:
  base_url: ${BASE_URL}
  security:
    cors:
      enabled: true
      path-pattern: "/**"
      allowed-origins:
        - ${FRONTEND_ORIGIN}
      allowed-methods:
        - "GET"
        - "POST"
        - "PUT"
        - "PATCH"
        - "DELETE"
        - "OPTIONS"
      allowed-headers:
        - "*"
      exposed-headers:
        - "Set-Cookie"
      allow-credentials: true
      max-age-seconds: 1800
